name: Sourcery

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sourcery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Sourcery
        uses: sourcery-ai/action@v1
        with:
          token: ${{ secrets.SOURCERY_TOKEN }}
